import { useState, useEffect, useRef } from 'react';
import { PI, CI, BC, BP, BD } from '../../assets/images/index.js';
import { PL } from '../../data/mocks/players.js';
import { tG } from '../../data/mocks/team.js';
import { sch } from '../../data/mocks/schedule.js';
import {
  C, ff, fd, tC, sC, sL, skC,
  I, Pill, Btn, Cd, Av, SH, PB, Rg, Sp, Bk, Hero, Strip,
} from '../../ui/index.js';

const HomeScreen = ({go})=>{const tips=["Marcus's shooting up 12%. AI recommends Complete Shooting Lab ($39.99) for his FT% goal.","Transition D needs work — try the Lockdown Defense System for team defensive goal.","Tyler's 3pt objective at 45%. Catch & Shoot helping — assign more drills."];const[ti,setTi]=useState(0);useEffect(()=>{const t=setInterval(()=>setTi(i=>(i+1)%tips.length),6000);return()=>clearInterval(t);},[]);return(<div style={{padding:"0 0 110px",animation:"fu .3s ease"}}>
<Hero src={BC} h={200}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",paddingTop:48,paddingBottom:16}}><div><p style={{color:"rgba(255,255,255,.6)",fontSize:12,margin:0,letterSpacing:1.5,textTransform:"uppercase",fontWeight:500}}>Welcome back</p><h1 style={{fontFamily:fd,fontSize:28,fontWeight:800,color:"#fff",margin:"4px 0 0",textShadow:"0 2px 12px rgba(0,0,0,.4)"}}>Coach Mike</h1></div><div style={{display:"flex",gap:10}}><button style={{width:44,height:44,borderRadius:14,background:"rgba(0,0,0,.3)",border:"1px solid rgba(255,255,255,.1)",backdropFilter:"blur(8px)",display:"flex",alignItems:"center",justifyContent:"center",position:"relative",cursor:"pointer"}}><I n="bell" s={20} c="#fff"/><div style={{position:"absolute",top:8,right:8,width:8,height:8,borderRadius:"50%",background:C.br}}/></button><Av ch="CM" sz={44} img={CI}/></div></div></Hero>
<div style={{padding:"0 20px"}}><Cd sx={{marginTop:-24,position:"relative",zIndex:2,marginBottom:20,background:`linear-gradient(135deg,${C.vi}08,${C.vi}04)`,border:`1px solid ${C.vi}18`}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:10}}><div style={{width:32,height:32,borderRadius:10,background:C.viS,display:"flex",alignItems:"center",justifyContent:"center"}}><I n="brain" s={16} c={C.vi}/></div><div><div style={{fontSize:12,fontWeight:700,color:C.vi,textTransform:"uppercase",letterSpacing:1}}>AI Insight</div><div style={{fontSize:11,color:C.sub}}>Based on team objectives</div></div></div><p style={{fontSize:14,color:C.ink,lineHeight:1.7,margin:0}}>{tips[ti]}</p><div style={{display:"flex",gap:5,marginTop:14}}>{tips.map((_,i)=><div key={i} style={{width:i===ti?20:6,height:6,borderRadius:3,background:i===ti?C.vi:`${C.vi}25`,transition:"all .4s"}}/>)}</div></Cd>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:28}}>{[{l:"Players",v:"12",i:"users",c:C.br},{l:"Sessions",v:"5",i:"cal",c:C.bl},{l:"Win Rate",v:"78%",i:"target",c:C.gn}].map((s,i)=><Cd key={i} sx={{textAlign:"center",padding:"16px 10px"}}><div style={{width:38,height:38,borderRadius:12,background:`${s.c}10`,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 8px"}}><I n={s.i} s={17} c={s.c}/></div><div style={{fontFamily:fd,fontSize:26,fontWeight:800,color:C.ink}}>{s.v}</div><div style={{fontSize:11,color:C.sub,marginTop:2}}>{s.l}</div></Cd>)}</div>
<Strip src={BP} label="Goals & Progress" icon="target" offset="-30%"/>
<SH title="Team Objectives" label="Manage" act={()=>{}}/><div style={{display:"flex",gap:10,overflowX:"auto",marginBottom:28,paddingBottom:6,marginRight:-20}}>{tG.map((g,i)=><Cd key={i} sx={{minWidth:130,flexShrink:0,padding:14,display:"flex",flexDirection:"column",alignItems:"center",gap:8}}><Rg v={g.p} sz={56} c={g.p>=75?C.gn:g.p>=40?C.am:C.br}/><div style={{fontSize:12,fontWeight:600,color:C.ink,textAlign:"center",lineHeight:1.3}}>{g.t}</div><div style={{fontSize:10,color:C.dim}}>{g.c}</div></Cd>)}</div>
<Strip src={BD} label="Today's Plan" icon="cal" offset="-40%"/>
<SH title="Today's Schedule" act={()=>go(2)}/>{sch.filter(s=>s.dt==="Today").map(s=><Cd key={s.id} sx={{display:"flex",alignItems:"center",gap:12,marginBottom:8,minHeight:64}}><div style={{width:44,height:44,borderRadius:13,background:`${tC[s.ty]}10`,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><I n={s.ty==="film"?"video":s.ty==="individual"?"users":"cal"} s={18} c={tC[s.ty]}/></div><div style={{flex:1,minWidth:0}}><div style={{fontSize:14,fontWeight:600,color:C.ink,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{s.ti}</div><div style={{fontSize:12,color:C.sub,marginTop:3}}>{s.tm} · {s.dur}{s.ct.length>0&&<span style={{color:C.bl}}> · {s.ct.length} content</span>}</div></div><I n="right" s={16} c={C.dim}/></Cd>)}
<Strip src={BP} label="Your Squad" icon="users" h={56} offset="-60%"/>
<SH title="Top Performers" act={()=>go(1)}/><div style={{display:"flex",gap:10,overflowX:"auto",marginRight:-20,paddingBottom:6}}>{PL.slice(0,4).map(p=><Cd key={p.id} sx={{minWidth:120,textAlign:"center",padding:"16px 14px",flexShrink:0}} tap={()=>go(1)}><Av ch={p.av} sz={46} img={p.img}/><div style={{fontSize:13,fontWeight:700,color:C.ink,marginTop:8}}>{p.nm.split(" ")[0]}</div><div style={{fontSize:11,color:C.sub,marginTop:2}}>{p.pos} · #{p.num}</div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:4,marginTop:8}}><span style={{fontFamily:fd,fontSize:20,fontWeight:800,color:C.ink}}>{p.rt}</span><span style={{fontSize:11,color:p.tr[0]==="+"?C.gT:C.ro,fontWeight:700}}>{p.tr}</span></div></Cd>)}</div></div></div>);};;

export default HomeScreen;
