import { useState, useEffect, useRef } from 'react';
import { mkt } from '../../data/mocks/content.js';
import { BD } from '../../assets/images/index.js';
import {
  C, ff, fd, tC, sC, sL, skC,
  I, Pill, Btn, Cd, Av, SH, PB, Rg, Sp, Bk, Hero, Strip,
} from '../../ui/index.js';

const PlayerProfileScreen = ({p,back})=>{const[tab,setTab]=useState("overview");return(<div style={{padding:"0 0 110px",animation:"fu .3s ease"}}><Hero src={BD} h={220}><div style={{paddingTop:48}}><Bk onClick={back} l="Roster"/></div><div style={{display:"flex",alignItems:"center",gap:16,paddingBottom:16}}><div style={{position:"relative"}}><Av ch={p.av} sz={68} img={p.img}/>{p.st==="injured"&&<div style={{position:"absolute",bottom:-2,right:-2,width:20,height:20,borderRadius:"50%",background:C.ro,border:`3px solid ${C.bg}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:"#fff",fontWeight:700}}>!</div>}</div><div style={{flex:1}}><h1 style={{fontFamily:fd,fontSize:24,fontWeight:800,color:"#fff",margin:0,textShadow:"0 2px 8px rgba(0,0,0,.5)"}}>{p.nm}</h1><div style={{display:"flex",gap:6,marginTop:6,alignItems:"center",flexWrap:"wrap"}}><Pill t={p.pos} c={C.br} b={C.brS}/><span style={{fontSize:13,color:"rgba(255,255,255,.7)"}}>#{p.num} · {p.yr} · {p.ag}</span>{p.st==="injured"&&<Pill t="Injured" c={C.ro} b={C.roS}/>}</div></div><div style={{textAlign:"center",background:"rgba(0,0,0,.4)",borderRadius:14,padding:"10px 14px",backdropFilter:"blur(8px)"}}><div style={{fontFamily:fd,fontSize:32,fontWeight:800,color:"#fff",lineHeight:1}}>{p.rt}</div><div style={{fontSize:12,fontWeight:700,color:p.tr[0]==="+"?C.gT:C.ro,marginTop:2}}>{p.tr}</div></div></div></Hero>
<div style={{display:"flex",gap:6,padding:"12px 20px",marginBottom:16,overflowX:"auto"}}>{["overview","objectives","stats","games","content","notes"].map(t=><button key={t} onClick={()=>setTab(t)} style={{padding:"10px 18px",borderRadius:12,fontSize:13,fontWeight:tab===t?700:500,fontFamily:ff,background:tab===t?C.br:"transparent",color:tab===t?"#fff":C.sub,border:tab===t?"none":`1px solid ${C.ln}`,cursor:"pointer",textTransform:"capitalize",whiteSpace:"nowrap",minHeight:44}}>{t}</button>)}</div>
<div style={{padding:"0 20px"}}>{tab==="overview"&&<><Cd sx={{marginBottom:12}}><p style={{fontSize:14,color:C.ink,lineHeight:1.7,margin:0}}>{p.bio}</p></Cd>{p.injury&&<Cd sx={{marginBottom:12,borderLeft:`3px solid ${C.ro}`}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><span style={{fontSize:18}}>🩹</span><span style={{fontSize:12,color:C.ro,fontWeight:700,textTransform:"uppercase",letterSpacing:1}}>Injury Report</span></div><div style={{fontSize:16,fontWeight:700,color:C.ink,marginBottom:6}}>{p.injury.type}</div><div style={{fontSize:13,color:C.sub}}>Since {p.injury.since} · Return: <span style={{color:C.gT,fontWeight:600}}>{p.injury.ret}</span> · {p.injury.note}</div></Cd>}<Cd sx={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><span style={{fontSize:13,fontWeight:700,color:C.ink}}>Rating Trend</span><span style={{fontSize:13,fontWeight:700,color:p.tr[0]==="+"?C.gT:C.ro}}>{p.tr} this month</span></div><Sp d={p.wk} c={C.br} h={52}/></Cd><Cd sx={{marginBottom:12}}><div style={{fontSize:13,fontWeight:700,color:C.ink,marginBottom:14}}>Skill Breakdown</div>{Object.entries(p.sk).map(([k,v])=><PB key={k} l={k} v={v} c={skC[k]}/>)}</Cd>{p.prog.length>0&&<Cd><div style={{fontSize:13,fontWeight:700,color:C.ink,marginBottom:10}}>Player Updates</div>{p.prog.map((pr,i)=><div key={i} style={{padding:"12px 0",borderTop:i?`1px solid ${C.ln}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:4}}><Pill t={pr.ty} c={pr.ty==="milestone"?C.gn:C.am} b={pr.ty==="milestone"?C.gnS:C.amS}/><span style={{fontSize:11,color:C.dim}}>{pr.d}</span></div><p style={{fontSize:14,color:C.ink,lineHeight:1.5,margin:0}}>{pr.x}</p></div>)}</Cd>}</>}
{tab==="objectives"&&<><Cd sx={{marginBottom:14}}><div style={{fontSize:13,fontWeight:700,color:C.ink,marginBottom:16}}>Player Objectives</div>{p.goals.map((g,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:14,marginBottom:16}}><Rg v={g.p} sz={58} c={g.p>=75?C.gn:g.p>=40?C.am:C.br}/><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.ink}}>{g.t}</div><div style={{fontSize:12,color:C.dim,marginTop:3}}>{g.c}</div></div></div>)}</Cd><Cd sx={{background:C.viS,border:`1px solid ${C.vi}20`}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:10}}><I n="brain" s={16} c={C.vi}/><span style={{fontSize:12,fontWeight:700,color:C.vi,textTransform:"uppercase",letterSpacing:1}}>AI Suggestions</span></div>{mkt.filter(m=>m.ai).slice(0,2).map(m=><div key={m.id} style={{display:"flex",alignItems:"center",gap:10,padding:"12px 0",borderTop:`1px solid ${C.vi}15`}}><span style={{fontSize:22}}>{m.em}</span><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:C.ink}}>{m.ti}</div><div style={{fontSize:11,color:C.vi,marginTop:2}}>{m.why}</div></div><span style={{fontFamily:fd,fontSize:16,fontWeight:800,color:C.br}}>${m.pr}</span></div>)}</Cd><Btn full sx={{marginTop:14}}><I n="plus" s={16} c={C.br}/>Add Objective</Btn></>}
{tab==="stats"&&<><Cd sx={{marginBottom:12}}><div style={{fontSize:13,fontWeight:700,color:C.ink,marginBottom:14}}>Season Averages</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10}}>{Object.entries(p.ss).map(([k,v],i)=>{const cs=[C.br,C.bl,C.gn,C.am,C.gn,C.vi,C.br];return <div key={k} style={{background:C.el,borderRadius:14,padding:"14px 8px",textAlign:"center"}}><div style={{fontFamily:fd,fontSize:24,fontWeight:800,color:cs[i%cs.length]}}>{v}</div><div style={{fontSize:10,color:C.dim,marginTop:4}}>{k}</div></div>;})}</div></Cd><Cd><div style={{fontSize:13,fontWeight:700,color:C.ink,marginBottom:10}}>Scoring Trend</div><Sp d={p.log.map(g=>g.p).reverse()} c={C.br} h={48}/></Cd></>}
{tab==="games"&&p.log.map((g,i)=><Cd key={i} sx={{marginBottom:10,borderLeft:`3px solid ${g.w?C.gn:C.ro}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><div><div style={{fontSize:15,fontWeight:700,color:C.ink}}>vs {g.vs}</div><div style={{fontSize:12,color:C.sub,marginTop:3}}>{g.d}</div></div><Pill t={g.w?"WIN":"LOSS"} c={g.w?C.gn:C.ro} b={g.w?C.gnS:C.roS}/></div><div style={{display:"flex",gap:8}}>{[{l:"PTS",v:g.p,c:C.br},{l:"AST",v:g.a,c:C.bl},{l:"REB",v:g.r,c:C.gn}].map((s,j)=><div key={j} style={{flex:1,background:C.el,borderRadius:12,padding:12,textAlign:"center"}}><div style={{fontFamily:fd,fontSize:22,fontWeight:800,color:s.c}}>{s.v}</div><div style={{fontSize:10,color:C.dim,marginTop:3}}>{s.l}</div></div>)}</div></Cd>)}
{tab==="content"&&<>{p.asgn.map((c,i)=><Cd key={i} sx={{display:"flex",alignItems:"center",gap:12,marginBottom:10,minHeight:64}}><div style={{width:42,height:42,borderRadius:12,background:c.ty==="video"?C.brS:c.ty==="drill"?C.gnS:C.blS,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><I n={c.ty==="video"?"play":c.ty==="drill"?"bolt":"book"} s={18} c={c.ty==="video"?C.br:c.ty==="drill"?C.gn:C.bl}/></div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.ink}}>{c.t}</div></div><Pill t={sL[c.s]} c={sC[c.s]} b={`${sC[c.s]}14`}/></Cd>)}<Btn full sx={{marginTop:8}}><I n="plus" s={16} c={C.br}/>Assign Content</Btn></>}
{tab==="notes"&&<>{p.notes.map((nt,i)=><Cd key={i} sx={{marginBottom:10,borderLeft:`3px solid ${C.vi}`}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:8}}><I n="book" s={14} c={C.vi}/><span style={{fontSize:13,color:C.vi,fontWeight:600}}>{nt.d}</span></div><p style={{fontSize:14,color:C.ink,lineHeight:1.6,margin:0}}>{nt.x}</p></Cd>)}<Btn full sx={{marginTop:6,background:C.cd}}><I n="plus" s={16} c={C.vi}/>Add Note</Btn></>}
<div style={{display:"flex",gap:10,marginTop:24}}><Btn full><I n="chat" s={18} c={C.br}/>Message</Btn><Btn full><I n="share" s={18} c={C.bl}/>Share</Btn></div></div></div>);};;

export default PlayerProfileScreen;
