import { CI, BC } from '../../assets/images/index.js';
import {
  C, ff, fd, tC, sC, sL, skC,
  I, Pill, Btn, Cd, Av, SH, PB, Rg, Sp, Bk, Hero, Strip,
} from '../../ui/index.js';

const MoreScreen = ()=>{const menu=[{i:"target",l:"Admin Dashboard",d:"Users, profiles & content"},{i:"chart",l:"Analytics",d:"Performance insights"},{i:"brain",l:"AI Coach",d:"Behavior-based suggestions"},{i:"star",l:"Subscription",d:"Pro Plan · Billing"},{i:"drip",l:"Drip Scheduler",d:"Content releases"},{i:"shop",l:"Marketplace",d:"Training packages"},{i:"flag",l:"Objectives",d:"Player & team goals"},{i:"building",l:"Club Management",d:"Multi-team ops"},{i:"video",l:"Film Room",d:"Game footage"},{i:"gear",l:"Settings",d:"Preferences"}];return(<div style={{padding:"0 0 110px",animation:"fu .3s ease"}}><Hero src={BC} h={140}><div style={{paddingTop:48,paddingBottom:16}}><h1 style={{fontFamily:fd,fontSize:28,fontWeight:800,color:"#fff",margin:0,textShadow:"0 2px 8px rgba(0,0,0,.5)"}}>More</h1></div></Hero><div style={{padding:"16px 20px 0"}}><Cd sx={{display:"flex",alignItems:"center",gap:14,marginBottom:24}}><div style={{position:"relative"}}><Av ch="CM" sz={60} img={CI}/><div style={{position:"absolute",bottom:-2,right:-2,width:20,height:20,borderRadius:8,background:C.am,border:`3px solid ${C.cd}`,display:"flex",alignItems:"center",justifyContent:"center"}}><I n="star" s={10} c="#fff"/></div></div><div><div style={{fontFamily:fd,fontSize:22,fontWeight:800,color:C.ink}}>Coach Mike</div><div style={{fontSize:13,color:C.sub,marginTop:3}}>Varsity Basketball · Pro Plan</div><div style={{marginTop:6}}><Pill t="Pro Member" c={C.am} b={C.amS}/></div></div></Cd>{menu.map((m,i)=><Cd key={i} tap={()=>{}} sx={{display:"flex",alignItems:"center",gap:12,padding:"14px 16px",marginBottom:6,minHeight:56}}><div style={{width:40,height:40,borderRadius:12,background:C.el,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><I n={m.i} s={18} c={C.br}/></div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.ink}}>{m.l}</div><div style={{fontSize:12,color:C.sub,marginTop:2}}>{m.d}</div></div><I n="right" s={16} c={C.dim}/></Cd>)}<div style={{textAlign:"center",marginTop:28}}><div style={{fontFamily:fd,fontSize:16,fontWeight:800,color:C.dim}}>Coach360</div><div style={{fontSize:11,color:C.dim,marginTop:3}}>v1.0.0 MVP</div></div></div></div>);};;

export default MoreScreen;
