import { useState, useEffect, useRef } from 'react';
import { BP } from '../../assets/images/index.js';
import { sch } from '../../data/mocks/schedule.js';
import {
  C, ff, fd, tC, sC, sL, skC,
  I, Pill, Btn, Cd, Av, SH, PB, Rg, Sp, Bk, Hero, Strip,
} from '../../ui/index.js';

const ScheduleScreen = ()=>{const days=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];const[sel,sSel]=useState(0);return(<div style={{padding:"0 0 110px",animation:"fu .3s ease"}}><Hero src={BP} h={160}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",paddingTop:48,paddingBottom:16}}><div><h1 style={{fontFamily:fd,fontSize:28,fontWeight:800,color:"#fff",margin:0,textShadow:"0 2px 8px rgba(0,0,0,.5)"}}>Schedule</h1><p style={{color:"rgba(255,255,255,.6)",fontSize:13,margin:"4px 0 0"}}>March 2026</p></div><Btn primary sx={{minHeight:44,padding:"10px 18px",fontSize:13}}><I n="plus" s={16} c="#fff"/>New</Btn></div></Hero><div style={{padding:"0 20px"}}><div style={{display:"flex",gap:6,margin:"16px 0 22px"}}>{days.map((d,i)=><button key={d} onClick={()=>sSel(i)} style={{flex:1,padding:"12px 0",borderRadius:14,textAlign:"center",cursor:"pointer",border:"none",background:sel===i?C.br:C.cd,minHeight:56}}><div style={{fontSize:10,color:sel===i?"rgba(255,255,255,.7)":C.dim,letterSpacing:1,marginBottom:3}}>{d}</div><div style={{fontSize:16,fontWeight:800,color:sel===i?"#fff":C.ink}}>{24+i}</div></button>)}</div>{sch.map(s=><Cd key={s.id} sx={{display:"flex",gap:14,marginBottom:10,borderLeft:`3px solid ${tC[s.ty]}`}}><div style={{minWidth:48,textAlign:"center"}}><div style={{fontSize:15,fontWeight:800,color:C.ink}}>{s.tm.split(" ")[0]}</div><div style={{fontSize:10,color:C.sub}}>{s.tm.split(" ")[1]}</div></div><div style={{flex:1}}><div style={{fontSize:15,fontWeight:600,color:C.ink,marginBottom:4}}>{s.ti}</div><div style={{display:"flex",gap:10}}><span style={{fontSize:12,color:C.sub,display:"flex",alignItems:"center",gap:3}}><I n="clock" s={12} c={C.dim}/>{s.dur}</span><span style={{fontSize:12,color:C.sub,display:"flex",alignItems:"center",gap:3}}><I n="users" s={12} c={C.dim}/>{s.n}</span></div>{s.ct.length>0&&<div style={{marginTop:8,display:"flex",gap:4,flexWrap:"wrap"}}>{s.ct.map((ct,j)=><span key={j} style={{fontSize:10,color:C.bl,background:C.blS,padding:"4px 10px",borderRadius:8}}>📎 {ct}</span>)}</div>}<div style={{marginTop:8}}><Pill t={s.ty} c={tC[s.ty]} b={`${tC[s.ty]}12`}/></div></div></Cd>)}</div></div>);};;

export default ScheduleScreen;
